apiVersion: v1
kind: Service
metadata:
  name: genshin-gallery-api
  labels:
    app: genshin-gallery-api
spec:
  ports:
    - port: 8000
  selector:
    app: genshin-gallery-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genshin-gallery-api
  labels:
    app: genshin-gallery-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genshin-gallery-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: genshin-gallery-api
    spec:
      containers:
      - image: museaqours/genshin-gallery-api:latest
        name: genshin-gallery-api
        ports:
          - containerPort: 8000
            name: genshin-gallery
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 3
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "100Mi"
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: MONGODB_URL
        - name: DB_SYNC_TOKEN
          valueFrom:
            secretKeyRef:
              name: genshin-picbed-secret
              key: DB_SYNC_TOKEN
